### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by jonassteinberg1** [vgrem/Office365-REST-Python-Client#118]
Every snippet from SO or from this repo's README throws the error below.  Here's my code:

```
import json

from office365.runtime.auth.authentication_context import AuthenticationContext
from office365.runtime.client_request import ClientRequest
from office365.runtime.utilities.request_options import RequestOptions

url = 'https://skydriveFoo.sharepoint.com/sites/Foo/Bar/SitePages/Home.aspx'
username = 'me'
password = 'secret'

ctx_auth = AuthenticationContext(url)
if ctx_auth.acquire_token_for_user(username, password):
    request = ClientRequest(ctx_auth)
    options = RequestOptions("{0}/_api/web/".format(url))
    options.set_header('Accept', 'application/json')
    options.set_header('Content-Type', 'application/json')
    data = request.execute_request_direct(options)
    s = json.loads(data.content)
    web_title = s['Title']
    print("Web title: " + web_title)
else:
    print(ctx_auth.get_last_error())
```

```
# error

Traceback (most recent call last):
  File "sharepoint_2.py", line 9, in <module>
    if ctx_auth.acquire_token_for_user(username, password):
  File "/Users/me/development/Foo/boxer/venv/lib/python3.7/site-packages/office365/runtime/auth/authentication_context.py", line 18, in acquire_token_for_user
    return self.provider.acquire_token()
  File "/Users/me/development/Foo/boxer/venv/lib/python3.7/site-packages/office365/runtime/auth/saml_token_provider.py", line 57, in acquire_token
    self.acquire_service_token(options)
  File "/Users/me/development/Foo/boxer/venv/lib/python3.7/site-packages/office365/runtime/auth/saml_token_provider.py", line 88, in acquire_service_token
    token = self.process_service_token_response(response)
  File "/Users/me/development/Foo/boxer/venv/lib/python3.7/site-packages/office365/runtime/auth/saml_token_provider.py", line 119, in process_service_token_response
    return token.text
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by jonassteinberg1** [comment]
- 2FA is not required
- this is Sharepoint Online 2016

**Comment by Shotgunosine** [comment]
I've got the same issue

**Comment by vgrem** [comment]
Greetings!

Most likely the error occurs since _invalid_ base url is provided for url: 

```
url = 'https://skydriveFoo.sharepoint.com/sites/Foo/Bar/SitePages/Home.aspx'
                                                    ^^^^^^^^^^^^^^^^^^^^^^^
                                                    this part needs to be omitted since it represents path to page url
```


The Url format for SharePoint REST service is as follows:

```
https://<tenant>.sharepoint.com/sites/<site>/_api/web?$select=Title
________________________________________________/ ___/ ____________/
                            |                      |           |
                   service root URL       source path    query options
```




**Solution**

Replace 

`url = 'https://skydriveFoo.sharepoint.com/sites/Foo/Bar/SitePages/Home.aspx'
`
with 

`url = 'https://skydriveFoo.sharepoint.com/sites/Foo/Bar'`

**Comment by jonassteinberg1** [comment]
wow; interesting.  okay, Thanks.  I'll see where that gets me.

**Comment by PawelJazukiewicz** [comment]
What solved the issue for me was correctly setting up the SSL module in the virtual environment, as per:
https://stackoverflow.com/questions/54135206/requests-caused-by-sslerrorcant-connect-to-https-url-because-the-ssl-module
