### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by archenroot** [vgrem/Office365-REST-Python-Client#121]
Hi, I am facing same issue as #118 , but cannot figure out how to change url in my case, tried already combinations.

When I open Sharepoint I get to this url:
https://collaboration.{domain}.{company}.{suffix}/Pages

When I access my project I get to following url:
https://collaboration.{domain}.{company}.{suffix}/sites/{project-name}/SharedDocuments

I tried following combinations:
https://collaboration.{domain}.{company}.{suffix}
https://collaboration.{domain}.{company}.{suffix}/Pages
https://collaboration.{domain}.{company}.{suffix}/sites/{project-name}
https://collaboration.{domain}.{company}.{suffix}/sites/{project-name}/ShareDocuments

None works... any ideas?

**Comment by mgaurav92** [comment]
Hi,

I'm getting the same error while calling the authentication method.
I'm directly passing the username and password, not using `settings.py`

Traceback (most recent call last):
File "sharepoint_file_operation.py", line 82, in <module>
if ctx_auth.acquire_token_for_user(username, password):
File "/Library/Python/2.7/site-packages/office365/runtime/auth/authentication_context.py", line 18, in acquire_token_for_user
return self.provider.acquire_token()
File "/Library/Python/2.7/site-packages/office365/runtime/auth/saml_token_provider.py", line 57, in acquire_token
self.acquire_service_token(options)
File "/Library/Python/2.7/site-packages/office365/runtime/auth/saml_token_provider.py", line 88, in acquire_service_token
token = self.process_service_token_response(response)
File "/Library/Python/2.7/site-packages/office365/runtime/auth/saml_token_provider.py", line 119, in process_service_token_response
return token.text
AttributeError: 'NoneType' object has no attribute 'text'

Actual Web URL : https://intranet.<company>.com/sites/abc/xyz/Shared%20Documents/Forms/AllItems.aspx?RootFolder="........."

URL combination that didn't work,
https://intranet.<company>.com/sites/abc/xyz/Shared%20Documents
https://intranet.<company>.com/sites/abc/xyz/
https://intranet.<company>.com/sites/abc

**Comment by smolanet** [comment]
The same problem here. Can anyone support?

**Comment by achyutaparida** [comment]
I am facing same issue can anyone help me?

**Comment by palomena** [comment]
Same problem here.

**Comment by KasperSvendsen** [comment]
I'm facing the same problem

**Comment by macthebadazz** [comment]
Same issue here .... anyone find a solution?

**Comment by josh-flori** [comment]
Same issue!

**Comment by beliaev-maksim** [comment]
just to ensure. MFA is not supported and will lead to auth issues.

**Comment by Dhyanesh97** [comment]
facing same issue with below code

from office365.runtime.auth.user_credential import UserCredential
from office365.sharepoint.client_context import ClientContext

site_url = "https://XXXX-my.sharepoint.com/personal/XXXXXXXX/"
username_env = 'XXXXX@XXXX.com'
password_env = 'XXXXXX'
relativeUrl = "Documents/XXXXXXX/" 

ctx = ClientContext(site_url).with_credentials(UserCredential(username_env, password_env))
web = ctx.web
ctx.load(web)
ctx.execute_query()


Above code is working in my (windows) local system but while running in docker gives error.
'NoneType' object has no attribute 'text'

Anyone found solution for this ?

**Comment by d6chaub** [comment]
same issue as you @Dhyanesh97.

When I run in docker or try to use this file upload functionality as part of an API and then test the endpoint with postman, I get " 'NoneType' object has no attribute 'text' " and it fails. I wish I had a clue. It works fine locally and passes all the connection tests. 

I see no choice for me but to change libraries.

**Comment by d6chaub** [comment]
update - I have found the issue.  @Dhyanesh97 

For anyone with this issue, please print out all of your environment variables to ensure that they are declared and not 'None'.

Be cautious using getenv as this will of course return None and pass it on if your env var dict doesn't contain what you think,

The stack trace for this error is very convoluted and blames flask and wsgi and so on, but ultimately it leads to the fact that the error message for this library is not very good for the circumstance of the url provided being a Nonetype.

I am on an enterprise account and therefore not allowed to make a patch myself due to legal issues, but propose the following change to the library to make a clearer error message for this case. 

in site-packages/office365/runtime/auth/providers/acs_token_provider.py - 
 def get_app_only_access_token(self):
        try:
            realm = self._get_realm_from_target_url()
            url_info = urlparse(self.url)
            return self._get_app_only_access_token(url_info.hostname, realm)
        except requests.exceptions.RequestException as e:
            self.error = e.response.text if e.response is not None else str(e)
            raise ValueError(self.error)

**Comment by vgrem** [comment]
Closing - `AttributeError: 'NoneType' object has no attribute 'text'` in `saml_token_provider.py` means the SAML token endpoint returned an empty body. This is Microsoft blocking the IDCRL/SAML auth protocol, permanently retired May 1, 2026 (MC1184649). The "works locally but fails in Docker" pattern reported here is typically caused by Docker's network/DNS resolving to a different endpoint or hitting a Microsoft conditional access policy that blocks legacy auth more aggressively in non-browser contexts.

`UserCredential`, `saml_token_provider.py`, and `acs_token_provider.py` have been removed from the library. Migrate to modern auth:


```python
# Non-interactive (MSAL ROPC)
ctx = ClientContext(url).with_username_and_password(tenant, client_id, username, password)

# Interactive (handles MFA, Conditional Access)
ctx = ClientContext(url).with_interactive(tenant, client_id)

# App-only — recommended for automation and Docker deployments
ctx = ClientContext(url).with_client_secret(tenant, client_id, client_secret)
ctx = ClientContext(url).with_client_certificate(tenant, client_id, thumbprint, cert_path)
```

On the URL question: always use the site root (`https://tenant.sharepoint.com/sites/project-name`), never a library path or document path.
