### ISSUE TITLE
Cannot install this library

### ISSUE THREAD

**Issue by Dylan-Jouin** [vgrem/office365-rest-python-client#158]
I tried to install Office365-REST-Python-Client but I have a error message

Traceback (most recent call last):
  File "c:\program files\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\Scripts\pip.exe\__main__.py", line 9, in <module>
TypeError: 'module' object is not callable

Do you have an idea ?
Thanks & Regards

**Comment by Dylan-Jouin** [comment]
Had to uninstall/install pip. And then it worked just fine
