### ISSUE TITLE
Large files fail to upload to SharePoint

### ISSUE THREAD

**Issue by rickyschools** [vgrem/Office365-REST-Python-Client#161]
I have a file that's over 500 MB that I need to upload to SharePoint. I'm hitting constraints using this library given an error message which states: `The server does not allow messages larger than 262144000 bytes`. Below is the full traceback.

I'm assuming this error is occurring because the file attempting to be uploaded is larger than the acceptable `chunksize` of 250MB for the REST API and Python client. 

I've been reviewing the codebase and documentation and am struggling to find a successful way to upload my file in chunks using your client library. Please don't take this as a slight; I'm happy to contribute on documentation if we can find resolution on this issue. My code snippet, which attempts the chunking process (3rd code snippet), is below.

My question for maintainers is two-fold:

1. Should end-users expect larger files not to be chunked via the Python Client (API wrapper). 

2. If yes to prior question, how would you recommend I leverage this library to upload large files to SharePoint. Below the traceback, you'll find my initial implementation (which should largely mimic the code found in the examples) which I've been using to perform uploads for smaller files.

**_**Traceback**_**
```
Traceback (most recent call last):
  File "/home/ricky/.conda/envs/bi-export-env/lib/python3.7/site-packages/bi_exporter/models/base_operator.py", line 84, in execute
    self.returns = self.callable_object(*self.callable_args, **self.callable_kwargs)
  File "/home/ricky/.conda/envs/bi-export-env/lib/python3.7/site-packages/bi_exporter/core/sharepoint.py", line 18, in _upload_process
    context.execute_query()
  File "/home/ricky/.conda/envs/bi-export-env/lib/python3.7/site-packages/office365/runtime/client_runtime_context.py", line 38, in execute_query
    self.pending_request.execute_query()
  File "/home/ricky/.conda/envs/bi-export-env/lib/python3.7/site-packages/office365/runtime/client_request.py", line 32, in execute_query
    return self.execute_pending_queries()
  File "/home/ricky/.conda/envs/bi-export-env/lib/python3.7/site-packages/office365/runtime/client_request.py", line 39, in execute_pending_queries
    self.process_payload_json(query, response)
  File "/home/ricky/.conda/envs/bi-export-env/lib/python3.7/site-packages/office365/runtime/client_request.py", line 50, in process_payload_json
    self.validate_response(response)
  File "/home/ricky/.conda/envs/bi-export-env/lib/python3.7/site-packages/office365/runtime/client_request.py", line 149, in validate_response
    raise ClientRequestException(*e.args, response=e.response)
office365.runtime.client_request_exception.ClientRequestException: ('-1, Microsoft.SharePoint.Client.InvalidClientQueryException', 'The request message is too big. The server does not allow messages larger than 262144000 bytes.', "400 Client Error: Bad Request for url: https://company.sharepoint.com/_api/Web/getfolderbyserverrelativeurl(directory_location)/Files/add(overwrite=true,url='report.csv')")
```

_**Initial implementation of function performing uploads to sharepoint**_
```
def _upload_process(local_path, ctx_client, sharepoint_directory):
    with open(local_path, 'rb') as file_to_upload:
        upload_content = file_to_upload.read()
    library = ctx_client.web.get_folder_by_server_relative_url(sharepoint_directory)
    context = library.context
    info = FileCreationInformation(url=os.path.basename(local_path), content=upload_content, overwrite=True)
    target_file = library.files.add(info)
    context.execute_query()
```

_**Chunking attempt**_
```
import os
import uuid

from office365.runtime.auth.authentication_context import AuthenticationContext
from office365.sharepoint.client_context import ClientContext
from office365.sharepoint.file import File


def sharepoint_auth(site, username, pw):
    ctx_auth = AuthenticationContext(url=site)
    if ctx_auth.acquire_token_for_user(username, pw):
        ctx_client = ClientContext(site, ctx_auth)
        return ctx_auth, ctx_client
    return ctx_auth


username = os.environ.get("SP_USER")
pw = os.environ.get("SP_PW")
site = os.environ.get("SP_PASS")
directory = os.environ.get("SP_PARENT_DIR")
upload_item = os.environ.get("SP_UPLOAD_ITEM")
desired_dest = os.environ.get("SP_CHILD_FOLDER")

upload_loc = os.path.join(directory, desired_dest)

auth, client = sharepoint_auth(site=site, username=username, pw=pw)
library = client.web.get_folder_by_server_relative_url(upload_loc)
context = library.context

chunksize = 50 * 1024  # 50 MB


chunks = list()
offset = 0
with open(upload_item, 'rb') as file_data:
    content = file_data.read()

total_size = len(content)

offsets = []
if total_size % chunksize != 0:
    offsets = [(x + 1) * chunksize for x in range(total_size // chunksize)] + [total_size]
else:
    offsets = [(x + 1) * chunksize for x in range(total_size // chunksize)]

sharepoint_file = File(context, os.path.basename(upload_item))
upload_id = uuid.uuid4()


for offset in offsets:
    if offsets.index(offset) == 0:
        sharepoint_file.start_upload(upload_id=upload_id, content=content)
    elif offsets.index(offset) == len(offsets):
        sharepoint_file.finish_upload(upload_id=upload_id, file_offset=offset, content=content)
    else:
        sharepoint_file.continue_upload(upload_id=upload_id, file_offset=offset, content=content)
```

Thank you in advance for your help and guidance. 

RS

**Comment by rickyschools** [comment]
While I know the code above is incorrect, I realized I was on an older release of this library. I bumped the install from `2.1.3` to `2.1.5`, but am now seeing some odd issues with uploads. 

Specifically, I'm able to upload a zip file that's 400+ MB with no problem. When I attempt to upload any CSV or XLSX file that's over 250 MB, I run into the same error I shared above. I'm unsure if the error is a result of something in the client library or the REST API itself. 

Here's the function I'm using to attempt the upload, which was shared above.

**_Initial implementation of function performing uploads to sharepoint_**
```
def _upload_process(local_path, ctx_client, sharepoint_directory):
    with open(local_path, 'rb') as file_to_upload:
        upload_content = file_to_upload.read()
    library = ctx_client.web.get_folder_by_server_relative_url(sharepoint_directory)
    context = library.context
    info = FileCreationInformation(url=os.path.basename(local_path), content=upload_content, overwrite=True)
    target_file = library.files.add(info)
    context.execute_query()
```

**Comment by vgrem** [comment]
Greetings!

Indeed, this kind of exception could occur in SharePoint Online if fie size exceeds  250 MB file limit, refer for instance, [this article](https://docs.microsoft.com/en-us/archive/blogs/sharepointdevelopersupport/always-use-file-chunking-to-upload-files-250-mb-to-sharepoint-online) for a more details.

For this scenario i would recommend to upload a file as fragments (chunks) via upload session API methods as demonstrated below.

> Note: those methods are supported by this library but due to a few bugs, please make sure to grab the latest version from GiHub (until  `2.1.6` will be released):
> 
> `pip install git+https://github.com/vgrem/Office365-REST-Python-Client.git `
> 


**Example**

Here is an example which demonstrates how to upload a file via session 


```
def upload_file_session(context, local_path, target_folder_url,chunk_size):
    upload_id = str(uuid.uuid4())
    f = open(local_path, 'rb')
    st = os.stat(local_path)

    # 1. create an empty file first
    info = FileCreationInformation()
    info.content = ""
    info.url = os.path.basename(local_path)
    info.overwrite = True
    target_folder = context.web.get_folder_by_server_relative_url(target_folder_url)
    target_file = target_folder.files.add(info)
    context.execute_query()

    # 2. upload a file via session
    target_file_url = os.path.basename(local_path)
    f_pos = 0
    for piece in read_in_chunks(f, size=chunk_size):
        if f_pos == 0:
            upload_result = target_folder.files.get_by_url(target_file_url).start_upload(upload_id, piece)
            context.execute_query()
        elif f_pos + len(piece) < st.st_size:
            upload_result = target_folder.files.get_by_url(target_file_url).continue_upload(upload_id, f_pos,
                                                                                            piece)
            context.execute_query()
        else:
            upload_result = target_folder.files.get_by_url(target_file_url).finish_upload(upload_id, f_pos, piece)
            context.execute_query()
        f_pos += len(piece)
```


**Usage**

```
 ctx = ClientContext(site_url, ctx_auth)
 size_4k = 1024 * 4
 path = "../data/SharePoint User Guide.docx"
 target_url = "/Shared Documents"
 upload_file_session(ctx, path, target_url, size_4k)
```
