### ISSUE TITLE
SSL certificate verify failed

### ISSUE THREAD

**Issue by platocha** [vgrem/Office365-REST-Python-Client#312]
Hi, I have an issue on my work computer with connecting to Sharepoint Online due to SSL issue. It works on my Mac without issues.

My simple code:
`site_url = 'https://{company}.sharepoint.com/sites/{site}'
client_credentials = ClientCredential(client_id, client_secret)
ctx = ClientContext(site_url).with_credentials(client_credentials)
web = ctx.web
ctx.load(web)
ctx.execute_query()
print("Web title: {0}".format(web.properties['Title']))`

Errors that I get:
`ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)
requests.exceptions.SSLError: HTTPSConnectionPool(host='accounts.accesscontrol.windows.net', port=443): Max retries exceeded with url: /76a2ae5a-9f00-4f6b-95ed-5d33d77c4d61/tokens/OAuth/2 (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),))`

I have tried disabling SSL ( #61 ), but something changed I believe. I have replaced 'get_pending_request()' with 'pending_request()', but with or without this line I get the same SSL error.

`site_url = 'https://{company}.sharepoint.com/sites/{site}'
client_credentials = ClientCredential(client_id, client_secret)
ctx = ClientContext(site_url).with_credentials(client_credentials)
ctx.pending_request().beforeExecute += disable_ssl
web = ctx.web
ctx.load(web)
ctx.execute_query()
print("Web title: {0}".format(web.properties['Title']))`

Thank you in advance for any help in resolving this issue. I was so happy that I finally found the code that is so extensive and works until I tried it on my work computer...

**Comment by coding724** [comment]
same issue here.. replaced et_pending_request() to pending_request() = False ... still having issues with SSL :/

**Comment by Klazer** [comment]
Also having the same issue. Haven't found any solutions or workarounds

**Comment by venkateshnyq550** [comment]
@vgrem 
Getting same SSL error

Reference: https://github.com/vgrem/Office365-REST-Python-Client/issues/61

>>> site_url = 'https://xxx.sharepoint.com/sites/Qlik_SE_APP_Mapping' 
>>> client_credentials = ClientCredential(client_id, client_secret) 
>>> ctx = ClientContext(site_url).with_credentials(client_credentials) 
>>> ctx.pending_request().beforeExecute += disable_ssl 
>>> web = ctx.web 
>>> ctx.load(web) 
<office365.sharepoint.client_context.ClientContext object at 0x7faf866aa7c0>
>>> ctx.execute_query() 
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 700, in urlopen
    self._prepare_proxy(conn)
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 996, in _prepare_proxy
    conn.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/airflow/.local/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

**Comment by vgrem** [comment]
Fixed in v3.0.0. `with_transport(verify=...)` now threads SSL verification settings into both the `RequestsTransport` session **and** MSAL token acquisition - the two-layer SSL problem is resolved:

```bash
pip install --upgrade office365-rest-python-client
```

```python
from office365.sharepoint.client_context import ClientContext

ctx = ClientContext(site_url)\
    .with_client_certificate(tenant, client_id, thumbprint, cert_path)\
    .with_transport(verify="/path/to/corporate-ca-bundle.crt")
```

Or via environment variable (also covers MSAL, no code change needed):
```bash
export REQUESTS_CA_BUNDLE=/path/to/corporate-ca-bundle.crt
```

Also: `ClientCredential` (ACS) used in this thread is permanently retired since April 2026 - `with_client_certificate` is the correct replacement. Related: #192, #382, #591, #609, #1004. Labels: `transport`, `legacy-auth`, `sharepoint`.
