### ISSUE TITLE
Install Fails with ModuleNotFoundError: No module named 'setuptools_rust'

### ISSUE THREAD

**Issue by Gcsaniz** [vgrem/Office365-REST-Python-Client#325]
Collecting cryptography<4,>=0.6 (from msal->Office365-REST-Python-Client)
  Using cached https://files.pythonhosted.org/packages/fa/2d/2154d8cb773064570f48ec0b60258a4522490fcb115a6c7c9423482ca993/cryptography-3.4.6.tar.gz
    Complete output from command python setup.py egg_info:
    
            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:
    
            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-hew_uff8/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'

**Comment by vgrem** [comment]
Closing - stale environment issue from 2021, no longer relevant. `cryptography` now ships pre-built wheels for all major platforms - `setuptools_rust` is not needed with any current pip version.

If you're still seeing this, you have an extremely outdated pip:

```
pip install --upgrade pip
pip install office365-rest-python-client
```

Minimum pip version to get pre-built wheels: `21.0+`. Current pip is `24.x` - just upgrade.
