### ISSUE TITLE
Excpetion MissingSchema raise if I try to delete a file version

### ISSUE THREAD

**Issue by andreas-j-hauser** [vgrem/Office365-REST-Python-Client#329]
Excpetion MissingSchema raise if I try to delete a file version. It looks for me, that attribute `resource_url` and/or `resource_path` of the object is missing:

```
 Traceback (most recent call last):
  File ".\venv\lib\site-packages\office365\runtime\client_request.py", line 74, in execute_query
    response = self.execute_request_direct(request)
  File ".\venv\lib\site-packages\office365\runtime\odata\odata_request.py", line 34, in execute_request_direct
    return super(ODataRequest, self).execute_request_direct(request)
  File ".\venv\lib\site-packages\office365\runtime\client_request.py", line 95, in execute_request_direct
    result = requests.post(url=request_options.url,
  File ".\venv\lib\site-packages\requests\api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File ".\venv\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File ".\venv\lib\site-packages\requests\sessions.py", line 528, in request
    prep = self.prepare_request(req)
  File ".\venv\lib\site-packages\requests\sessions.py", line 456, in prepare_request
    p.prepare(
  File ".\venv\lib\site-packages\requests\models.py", line 316, in prepare
    self.prepare_url(url, params)
  File ".\venv\lib\site-packages\requests\models.py", line 390, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None': No schema supplied. Perhaps you meant http://None?
```

My code
```
file_object = context.web.get_file_by_server_relative_url(relative_file_url)

versions = file_object.versions
context.load(versions)
context.execute_query()

for index, version in enumerate(versions):
    version.delete_object()
    context.execute_query()
    break
```

Exception occurs if the second last line is executed. It is a bug or am I doing something wrong?

I use Python 3.8.1 / office365 2.3.1

**Comment by vgrem** [comment]
Greeting @andreas-j-hauser

thank you for catching this bug!

It has been resolved in the [`2.3.2` release](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.3.2)
