### ISSUE TITLE
Memory Error - ctx.web.get_folder_by_server_relative_url(target).files.create_upload_session when uploading large files

### ISSUE THREAD

**Issue by techy007** [vgrem/Office365-REST-Python-Client#342]
I am trying to upload large files (this is over 2GB).  I get a memory error as it appears the code is creating an object containing the data to upload rather than uploading in chunks.

My code is
`context_auth = AuthenticationContext(url=site_url)
context_auth.acquire_token_for_user(username=myuser,password=mypass)
size_100Mb = 1000000
result_file = ctx.web.get_folder_by_server_relative_url(target).files.create_upload_session(local, size_100Mb, print_upload_progress)
ctx.execute_query()`

where
`def print_upload_progress(offset):
    print("Uploaded '{0}' bytes...".format(offset))`

Traceback
_**Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\username\PycharmProjects\project\testupload.py", line 161, in <module>
    ctx.execute_query()
  File "C:\Users\username\venvs\django\lib\site-packages\office365\runtime\client_runtime_context.py", line 133, in execute_query
    self.pending_request().execute_query()
  File "C:\Users\username\venvs\django\lib\site-packages\office365\runtime\client_request.py", line 85, in execute_query
    self.afterExecute.notify(response)
  File "C:\Users\username\venvs\django\lib\site-packages\office365\runtime\types\EventHandler.py", line 18, in notify
    listener(*args, **kwargs)
  File "C:\Users\username\venvs\django\lib\site-packages\office365\runtime\client_runtime_context.py", line 122, in _process_response
    action(response)
  File "C:\Users\username\venvs\django\lib\site-packages\office365\sharepoint\actions\upload_session.py", line 57, in _build_upload_session_query
    upload_result = self.file.continue_upload(self._upload_id, f_pos, piece)
  File "C:\Users\username\venvs\django\lib\site-packages\office365\sharepoint\files\file.py", line 241, in continue_upload
    self.context.add_query(qry)
  File "C:\Users\username\venvs\django\lib\site-packages\office365\runtime\client_runtime_context.py", line 142, in add_query
    self.pending_request().add_query(query, to_begin)
  File "C:\Users\username\venvs\django\lib\site-packages\office365\runtime\client_request.py", line 55, in add_query
    self._queries.append(query)
MemoryError**_

For reference, I found some code that does work on the another site.  This allows the file to upload.

`def upload_file_session(context, local_path, target_folder_url, chunk_size):
    try:
        upload_id = str(uuid.uuid4())
        f = open(local_path, 'rb')
        st = os.stat(local_path)

        # 1. create an empty file first
        info = FileCreationInformation()
        info.content = ""
        info.url = os.path.basename(local_path)
        info.overwrite = False
        target_folder = context.web.get_folder_by_server_relative_url(target_folder_url)
        target_file = target_folder.files.add(info)
        context.execute_query()

        # 2. upload a file via session
        target_file_url = os.path.basename(local_path)
        f_pos = 0
        for piece in read_in_chunks(f, size=chunk_size):
            if f_pos == 0:
                upload_result = target_folder.files.get_by_url(target_file_url).start_upload(upload_id, piece)
                context.execute_query()
            elif f_pos + len(piece) < st.st_size:
                upload_result = target_folder.files.get_by_url(target_file_url).continue_upload(upload_id, f_pos,
                                                                                                piece)
                context.execute_query()
            else:
                upload_result = target_folder.files.get_by_url(target_file_url).finish_upload(upload_id, f_pos, piece)
                context.execute_query()
            f_pos += len(piece)
        f.close()
    except Exception as e:
        raise e`

**Comment by vgrem** [comment]
Hey,

thank you for reporting it,  `FileCollection.create_upload_session` method has been enhanced in terms of memory consumption.

A duplicated thread: #376
