### ISSUE TITLE
ModuleNotFoundError: No module named 'generator' with version 2.3.6 (no problem with 2.3.5)

### ISSUE THREAD

**Issue by zokrisd** [vgrem/Office365-REST-Python-Client#402]
Install Office365-REST-Python-Client==2.3.6

Then run the following:

$ python
Python 3.7.10 (default, Feb 20 2021, 21:17:23)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from office365.graph_client import GraphClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/office365_env3.7/lib/python3.7/site-packages/office365/graph_client.py", line 2, in <module>
    from office365.directory.audit.audit_log_root import AuditLogRoot
  File "/tmp/office365_env3.7/lib/python3.7/site-packages/office365/directory/audit/audit_log_root.py", line 2, in <module>
    from office365.directory.audit.provisioningObjectSummary import ProvisioningObjectSummary
  File "/tmp/office365_env3.7/lib/python3.7/site-packages/office365/directory/audit/provisioningObjectSummary.py", line 1, in <module>
    from generator.templates.entity_type import EntityType
ModuleNotFoundError: No module named 'generator'

Rather install Office365-REST-Python-Client==2.3.5 (where the same import works):

$ python
Python 3.7.10 (default, Feb 20 2021, 21:17:23)
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from office365.graph_client import GraphClient
>>>

Seems that package generator is missing from 2.3.6

**Comment by vgrem** [comment]
Greetings,

thank you for reporting it, it has been confirmed as a bug and resolved in [the latest release](https://github.com/vgrem/Office365-REST-Python-Client/tree/2.3.7)
