### ISSUE TITLE
Something wrong with OneDrive api

### ISSUE THREAD

**Issue by underthestars-zhy** [vgrem/Office365-REST-Python-Client#436]
```python
import msal
from office365.graph_client import GraphClient


def acquire_token_func():
    """
    Acquire token via MSAL
    """
    authority_url = 'https://login.microsoftonline.com/xxxx'
    app = msal.ConfidentialClientApplication(
        authority=authority_url,
        client_id='xxxx',
        client_credential='xxxxx'
    )
    token = app.acquire_token_for_client(scopes=["https://graph.microsoft.com/.default"])
    return token


print(acquire_token_func())
tenant_name = "contoso.onmicrosoft.com"
client = GraphClient(acquire_token_func)
drives = client.drives.get().execute_query()
for drive in drives:
    print("Drive url: {0}".format(drive.web_url))
```

**I can get the token**, but then something is wrong.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/office365/runtime/client_request.py", line 94, in execute_query
    response.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0/drives

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zhuhaoyumbp15/Desktop/UTS/OneDrive/main.py", line 22, in <module>
    drives = client.drives.get().execute_query()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/office365/runtime/client_object.py", line 41, in execute_query
    self.context.execute_query()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/office365/runtime/client_runtime_context.py", line 132, in execute_query
    self.pending_request().execute_query()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/office365/runtime/client_request.py", line 98, in execute_query
    raise ClientRequestException(*e.args, response=e.response)
office365.runtime.client_request_exception.ClientRequestException: ('AccessDenied', 'Either scp or roles claim need to be present in the token.', '403 Client Error: Forbidden for url: https://graph.microsoft.com/v1.0/drives')

**Comment by peraltae** [comment]
I'm having the same issue. Eager to see if this gets resolved.

**Comment by vgrem** [comment]
Greetings,

most likely application has not been configured properly. 

A few things to verify:

- for [`List available drives` endpoint](https://docs.microsoft.com/en-us/graph/api/drive-list?view=graph-rest-1.0&tabs=http)
 one of the following application permissions needs to be granted:  `Files.Read.All, Files.ReadWrite.All, Sites.Read.All, Sites.ReadWrite.All`

- ensure [Grant tenant-wide admin consent to an application](https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/grant-admin-consent)


JWT token for client credentials could also be verified in terms if it contains `roles` property by examining it, for instance, via [jwt.io](https://jwt.io/)

**Comment by vgrem** [comment]
Closing - either `scp` or `roles` claim need to be present in the token means the Azure AD app registration is missing the required API permissions or admin consent was not granted.

Checklist:

1. In Azure Portal → App registrations → your app → API permissions

2. Add application permissions (not delegated): `Files.Read.All` or `Files.ReadWrite.All`

3. Click Grant admin consent for {tenant} - this is mandatory for application permissions, they don't work without it

4. Verify the token contains a roles claim at [jwt.io](https://jwt.io/)

Also note: `GraphClient(acquire_token_func)` with a custom MSAL function still works, but the built-in builder is cleaner and avoids boilerplate:

```python
client = GraphClient(tenant="contoso.onmicrosoft.com")\
    .with_client_secret(client_id, client_secret)
```
