### ISSUE TITLE
Error when downloading file: json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

### ISSUE THREAD

**Issue by RobinVds** [vgrem/Office365-REST-Python-Client#466]
I'm sometimes receiving the following error when trying to download a file from SharePoint:

```

	
Traceback (most recent call last):
File "/var/task/sharepoint_information_extractor/engines/sharepoint.py", line 80, in download_file
file.download(
File "/var/task/office365/runtime/client_object.py", line 41, in execute_query
self.context.execute_query()
File "/var/task/office365/runtime/client_runtime_context.py", line 132, in execute_query
self.pending_request().execute_query()
File "/var/task/office365/runtime/client_request.py", line 92, in execute_query
self.beforeExecute.notify(request)
File "/var/task/office365/runtime/types/EventHandler.py", line 18, in notify
listener(*args, **kwargs)
File "/var/task/office365/sharepoint/client_context.py", line 192, in _build_modification_query
self.ensure_form_digest(request)
File "/var/task/office365/sharepoint/client_context.py", line 151, in ensure_form_digest
self._ctx_web_info = self.get_context_web_information()
File "/var/task/office365/sharepoint/client_context.py", line 159, in get_context_web_information
json = response.json()
File "/var/task/requests/models.py", line 910, in json
return complexjson.loads(self.text, **kwargs)
File "/var/lang/lib/python3.8/json/__init__.py", line 357, in loads
return _default_decoder.decode(s)
File "/var/lang/lib/python3.8/json/decoder.py", line 340, in decode
raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)
```

**Comment by ffcro3** [comment]
Any updates? Trying to do anything after the auth and no results.

**Comment by anais-surrusca** [comment]
I'm also facing this issue, trying to add a folder. Does somebody have any news ?

**Comment by ArunJRK** [comment]
Still Facing the issue. Any Solutions?

**Comment by adamerose** [comment]
I'm having the same issue. It doesn't happen on all URLs though, seems to be triggered by having symbols in the path name like `#`
