### ISSUE TITLE
🐛 Bug introduced in patch update 2.3.12 when retrieving SharePoint list items

### ISSUE THREAD

**Issue by jjloneman** [vgrem/Office365-REST-Python-Client#524]
## 🐛 Bug

When upgrading from `2.3.11` to `2.3.12`, without changing any of my code to retrieve list items from SharePoint, I received the following error:

```python
Traceback (most recent call last):
  ...
  File "C:\...\venv\lib\site-packages\office365\runtime\client_runtime_context.py", line 139, in execute_query
    self.pending_request().execute_query()
  File "C:\...\venv\lib\site-packages\office365\runtime\client_request.py", line 84, in execute_query
    raise ClientRequestException(*e.args, response=e.response)
office365.runtime.client_request_exception.ClientRequestException: (
  '-1, Microsoft.SharePoint.SPException',
  "The field or property 'Comments' does not exist.",
  "400 Client Error: Bad Request for url: https://.../_api/Web/lists/GetById('...')/items?$select=Comments,Title&$expand=Comments,Title"
)
```

## 🔍 Investigation

When upgrading, I noticed that the generated url changed to include the `$expand` query param:

```diff
- # Generated by 2.3.11
- https://.../_api/Web/lists/GetById('...')/items?$select=Comments,Title
+ # Generated by 2.3.12
+ https://.../_api/Web/lists/GetById('...')/items?$select=Comments,Title&$expand=Comments,Title
```

Looking at the code that was changed in `2.3.12`, it looks like the issue is here:

https://github.com/vgrem/Office365-REST-Python-Client/blob/2.3.12/office365/runtime/odata/query_options.py#L20

where in the expression on line 20:

```python
if isinstance(client_object, ClientObjectCollection)
```

`client_object` seems to have been accidentally used instead of `val`.

After modifying the source code:

```diff
class QueryOptions(object):

    @staticmethod
    def build(client_object, properties_to_include):
        """
        :param office365.runtime.client_object.ClientObject client_object: Client object
        :param list[str] properties_to_include: The list of properties to include
        """
        query = QueryOptions()
        for name in properties_to_include:
            val = client_object.get_property(name)
            from office365.runtime.client_object import ClientObject
            from office365.runtime.client_object_collection import ClientObjectCollection
-            if isinstance(client_object, ClientObjectCollection) or \
+            if isinstance(val, ClientObjectCollection) or \
                isinstance(val, ClientObject) or name == "Properties":
                query.expand.append(name)
            query.select.append(name)
        return query
```

the url is generated as expected, without the `$expand` query param, and I don't receive an HTTP 400 error.

**Comment by vgrem** [comment]
Thank you for catching this bug and the beautiful report! 
It has been resolved in [`2.3.13` version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.3.13).
