### ISSUE TITLE
I am getting json issue while uploading a file

### ISSUE THREAD

**Issue by rgannarapu** [vgrem/Office365-REST-Python-Client#547]
Hello,

I am trying to upload a file to sharepoint but I am getting some json error which I figure out. Someone please help me in solving this.

code:
```
from office365.runtime.auth.authentication_context import AuthenticationContext
from office365.sharepoint.client_context import ClientContext
import os

baseurl = 'https://<company>.sharepoint.com'
basesite = '/personal/xyz/Documents/Documents' 
siteurl = baseurl + basesite 

localpath = "index2.py"
remotepath = "/personal/xyz/Documents/Documents/index2.py"

ctx_auth = AuthenticationContext(baseurl)
ctx_auth.acquire_token_for_user(username, password)
ctx = ClientContext(siteurl, ctx_auth)
with open(localpath, 'rb') as content_file:
    file_content = content_file.read()

dir, name = os.path.split(remotepath)
file = ctx.web.get_folder_by_server_relative_url(dir).upload_file(name, file_content).execute_query()
```
I am getting below error
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "\\cntr\workstationdfs\RedirectedFolders$\n080892\Desktop\S3-onedrive\index5.py", line 20, in <module>
    file = ctx.web.get_folder_by_server_relative_url(dir).upload_file(name, file_content).execute_query()    
  File "C:\Program Files\Python310\lib\site-packages\office365\runtime\client_object.py", line 52, in execute_query
    self.context.execute_query()
  File "C:\Program Files\Python310\lib\site-packages\office365\runtime\client_runtime_context.py", line 142, 
in execute_query
    self.pending_request().execute_query()
  File "C:\Program Files\Python310\lib\site-packages\office365\runtime\client_request.py", line 80, in execute_query
    self.beforeExecute.notify(request)
  File "C:\Program Files\Python310\lib\site-packages\office365\runtime\types\event_handler.py", line 21, in notify
    listener(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\office365\sharepoint\client_context.py", line 260, in _build_modification_query
    self.ensure_form_digest(request)
  File "C:\Program Files\Python310\lib\site-packages\office365\sharepoint\client_context.py", line 175, in ensure_form_digest
    self._ctx_web_info = self.get_context_web_information(request_options=request_options)
  File "C:\Program Files\Python310\lib\site-packages\office365\sharepoint\client_context.py", line 186, in get_context_web_information
    json = response.json()
  File "C:\Program Files\Python310\lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by tomcubed** [comment]
Also experiencing a similar issue when installing the most recent version from git.

**Comment by wOL-Lucas** [comment]
Getting almost the same error. I'm trying to download files from Sharepoint and then I get this: "requests.exceptions.JSONDecodeError: Expecting value: line 2 column 1 (char 2)".

**Comment by Bernardo-Rufino** [comment]
Same problem here @vgrem, can you check it out?

**Comment by mkkubins** [comment]
I have the same error when I am trying to upload the data to the SharePoint using `.execute_query()`

`raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)`

**Comment by cframirezg** [comment]
Similar error here while uploading files to sharepoint:

  File "/home/airflow/.local/lib/python3.7/site-packages/office365/sharepoint/client_context.py", line 133, in request_form_digest
    json = response.json()
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Extra data: line 1 column 5 (char 4)

**Comment by RohitMidha23** [comment]
Has a fix been found for this? @vgrem

**Comment by cframirezg** [comment]
Hi,

Not yet. Sorry. It's an intermitent issue so we manage through retrying
________________________________
De: RohitMidha23 ***@***.***>
Enviado: sábado, 23 de septiembre de 2023 10:25 a. m.
Para: vgrem/Office365-REST-Python-Client ***@***.***>
Cc: cframirezg ***@***.***>; Comment ***@***.***>
Asunto: Re: [vgrem/Office365-REST-Python-Client] I am getting json issue while uploading a file (Issue #547)


Has a fix been found for this? @vgrem<https://github.com/vgrem>

**Comment by vgrem** [comment]
Closing - `JSONDecodeError: Expecting value: line 1 column 1` on `get_context_web_information` means SharePoint returned an empty body — the authentication silently failed and SharePoint returned a `401` with no JSON content to parse. In v3.0.0, `acquire_token_for_user` and `AuthenticationContext` have been removed - they raised this exact failure silently before.

**Two issues in the code:**

**1. Wrong URL for personal OneDrive** - `/personal/xyz/Documents/` is a OneDrive personal path. `ClientContext` targets SharePoint team sites. Use `GraphClient` for personal OneDrive:

```python
from office365.graph_client import GraphClient

client = GraphClient(tenant).with_interactive(client_id)

with open("index2.py", "rb") as f:
    client.me.drive.root\
        .get_by_path("Documents")\
        .upload_file("index2.py", f)\
        .execute_query()
```

**2. `acquire_token_for_user` is retired** - permanently retired May 2026. For SharePoint team sites, use:

```bash
pip install --upgrade office365-rest-python-client
```

```python
from office365.sharepoint.client_context import ClientContext

ctx = ClientContext("https://company.sharepoint.com/sites/mysite")\
    .with_client_certificate(tenant, client_id, thumbprint, cert_path)

with open("index2.py", "rb") as f:
    ctx.web.get_folder_by_server_relative_url("/sites/mysite/Shared Documents")\
        .upload_file("index2.py", f).execute_query()
```

Related: #267, #308, #334.
