### ISSUE TITLE
Get mail Error: 'dict' object is not callable

### ISSUE THREAD

**Issue by GHA193** [vgrem/Office365-REST-Python-Client#556]
Hi team,
* python version: Python 3.7.4
* package version: Office365-REST-Python-Client-2.3.13
* Description:
I try to get the mail in the mailbox, the error message is as follows. Do you know the reason please? Thanks in advance.
```
Traceback (most recent call last):
  File "G:/xxxxxxx/xxxxxx.py", line 416, in <module>
    email_read_graph()
  File "G:/xxxxxxx/xxxxxx.py", line 182, in email_read_graph
    messages = client.users[mail_address].mail_folders['INBOX'].messages.top(5).get().execute_query()
  File "C:\Python37\lib\site-packages\office365\runtime\client_object.py", line 52, in execute_query
    self.context.execute_query()
  File "C:\Python37\lib\site-packages\office365\runtime\client_runtime_context.py", line 142, in execute_query
    self.pending_request().execute_query()
  File "C:\Python37\lib\site-packages\office365\runtime\client_request.py", line 81, in execute_query
    response = self.execute_request_direct(request)
  File "C:\Python37\lib\site-packages\office365\runtime\odata\odata_request.py", line 38, in execute_request_direct
    return super(ODataRequest, self).execute_request_direct(request)
  File "C:\Python37\lib\site-packages\office365\runtime\client_request.py", line 93, in execute_request_direct
    self.context.authenticate_request(request)
  File "C:\Python37\lib\site-packages\office365\graph_client.py", line 96, in authenticate_request
    token_json = self._acquire_token_callback()
TypeError: 'dict' object is not callable
```
* Below is the code in my program.
```
def acquire_token(tenant_id, client_id, client_secret):
    authority_url = f'https://login.microsoftonline.com/{tenant_id}'
    app = msal.ConfidentialClientApplication(
        authority=authority_url,
        client_id=f'{client_id}',
        client_credential=f'{client_secret}'
    )
    token = app.acquire_token_for_client(scopes=["https://graph.microsoft.com/.default"])
    return token

def email_read_graph():
    tenant_id = tenantid
    client_id = clientid
    client_secret = clientsecret
    mail_address = targetmail

    token = acquire_token(tenant_id, client_id, client_secret)
    print(token)

    client = GraphClient(token)
    messages = client.users[mail_address].mail_folders['INBOX'].messages.top(5).get().execute_query()
    # messages = client.me.messages.get().execute_query()

    for mail in messages:
        print(mail.properties) 
```

* My request in Graph Explorer is successful.
![image](https://user-images.githubusercontent.com/24401268/186838699-4fa1498b-15fa-4142-ac63-6955cc7c180f.png)

**Comment by vgrem** [comment]
Hi, 

`GraphClient` constructor expects token function to be passed as a _callback_ arg.   

The list of changes:

- adjust `acquire_token` method to be _parameterless_: def  `acquire_token():`

- pass `acquire_token` into  `GraphClient` constructor:  `client = GraphClient(acquire_token)`

**Comment by GHA193** [comment]
Got it. Thank you, vgrem.
