### ISSUE TITLE
scopes = [f"{self.url}/.default"] syntax issue

### ISSUE THREAD

**Issue by rodricksprem** [vgrem/Office365-REST-Python-Client#575]
we are using python 2.7.5 and Office365_REST_Python_Client-2.3.14-py3-none-any.whl.
but we are getting below error. please let me know how to resolve this
Traceback (most recent call last):
  File "new_sharepoint.py", line 4, in <module>
    from office365.sharepoint.client_context import ClientContext
  File "/home/svc-oicdev/.local/lib/python2.7/site-packages/office365/sharepoint/client_context.py", line 2, in <module>
    from office365.runtime.auth.authentication_context import AuthenticationContext
  File "/home/svc-oicdev/.local/lib/python2.7/site-packages/office365/runtime/auth/authentication_context.py", line 33
    scopes = [f"{self.url}/.default"]

**Comment by kellerza** [comment]
f-strings are only supported in Python 3

**Comment by vgrem** [comment]
This issue has been addresed in [`2.5.0` version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.5.0) and should no longer occur in Python 2.7
