### ISSUE TITLE
Lack Unicode support: UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

### ISSUE THREAD

**Issue by hsluoyz** [vgrem/Office365-REST-Python-Client#62]
Hi,

My Office 365 is in Chinese language. When I run the example: ``examples\user_group_operations.py``, it gave me the error:

```
C:\Python27\python.exe J:/github_repos/Office365-REST-Python-Client/examples/user_group_operations.py
Traceback (most recent call last):
  File "J:/github_repos/Office365-REST-Python-Client/examples/user_group_operations.py", line 43, in <module>
    read_groups(ctx)
  File "J:/github_repos/Office365-REST-Python-Client/examples/user_group_operations.py", line 13, in read_groups
    print("Group title: {0}".format(group.properties["Title"]))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)

Process finished with exit code 1
```

When I debug the code, I found that the returned groups contain Chinese characters, which causes the error.

```python
def read_groups(ctx):
    """Read site groups example"""
    groups = ctx.web.site_groups
    ctx.load(groups)
    ctx.execute_query()

    for group in groups:
        print("Group title: {0}".format(group.properties["Title"]))  # <---- here contains non-English chars
```

Can you add the Unicode support for this library? Thanks.

**Comment by hsluoyz** [comment]
I solved this issue by adding the following code to ``examples/setting.py``:

```python
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```
