### ISSUE TITLE
checkout_page  AttributeError: 'NoneType' object has no attribute 'get_by_id'`

### ISSUE THREAD

**Issue by jerry-bonner** [vgrem/Office365-REST-Python-Client#730]
Hello,

I'm trying to update the content of a site page (I would appreciate an example). My understanding is that a checkout should be done first.  When calling checkout_page(), I get the following error. However, the page is indeed actually checked out.

`>>> file = ctx.site_pages.get().execute_query().pages.get_by_name('JerryTest2.aspx').get().execute_query()
>>> file.checkout_page().execute_query()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jbonner/GIT/python-sharepoint/.venv/lib/python3.11/site-packages/office365/runtime/client_object.py", line 47, in execute_query
    self.context.execute_query()
  File "/Users/jbonner/GIT/python-sharepoint/.venv/lib/python3.11/site-packages/office365/runtime/client_runtime_context.py", line 187, in execute_query
    self.pending_request().execute_query(qry)
  File "/Users/jbonner/GIT/python-sharepoint/.venv/lib/python3.11/site-packages/office365/runtime/client_request.py", line 59, in execute_query
    self.process_response(response, query)
  File "/Users/jbonner/GIT/python-sharepoint/.venv/lib/python3.11/site-packages/office365/runtime/odata/request.py", line 70, in process_response
    self.map_json(response.json(), return_type, json_format)
  File "/Users/jbonner/GIT/python-sharepoint/.venv/lib/python3.11/site-packages/office365/runtime/odata/request.py", line 83, in map_json
    return_type.set_property(k, v, False)
  File "/Users/jbonner/GIT/python-sharepoint/.venv/lib/python3.11/site-packages/office365/sharepoint/publishing/pages/metadata.py", line 151, in set_property
    self._resource_path = self.parent_collection.get_by_id(value).resource_path
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get_by_id'`

**Comment by vgrem** [comment]
Thank you for reporting this error, it has been addressed in [`2.5.1` version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.5.1).
