### ISSUE TITLE
'codec can't decode byte 0x8f in position 24' when initializing with binary certificate

### ISSUE THREAD

**Issue by sagimann** [vgrem/Office365-REST-Python-Client#732]
Hello,
I'm following the [integration instructions](https://learn.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread#setting-up-an-azure-ad-app-for-app-only-access) from Microsoft for the first time and have created a .cer + .pfx file as per their instructions. However, I can't get past `ClientContext.with_client_certificate` call. The error I'm getting is:

```
Traceback (most recent call last):
  File "C:\Users\xxxxx\venv\Lib\site-packages\office365\runtime\auth\authentication_context.py", line 44, in with_client_certificate
    private_key = f.read()
                  ^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.1520.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 24: character maps to <undefined>
python-BaseException
```

Why does the client assume the certificate is a text file whereas Microsoft instructions the creation of a binary PEM file? And.. how do I resolve this?

**Comment by vgrem** [comment]
Greetings,

it appears the error occurs since certificate file encoding could not be properly determined. Please refer this thread with alternative solution: #763

**Comment by vgrem** [comment]
Closing due to inactivity
