### ISSUE TITLE
Chunked downloading of large files from SPO using 'download_session()' broken after 2.4.1

### ISSUE THREAD

**Issue by pspot2** [vgrem/Office365-REST-Python-Client#748]
Hi,

after upgrading from 2.4.1 to the latest version (currently 2.4.4) the code for chunked downloading (using `download_session()`) of large files from a Sharepoint Online document library stopped working.

The code:

```
ctx_credentials = ClientCredential(<client_id>, <client_secret>)
ctx = ClientContext("https://mytenant.sharepoint.com/sites/mysite").with_credentials(ctx_credentials)
ctx.load(ctx.web)
ctx.execute_query()
source_file = ctx.get_file_by_server_relative_path("/sites/mysite/mydoclib/myfile.csv")
source_file.download_session(local_file_handle, download_progress_callback, chunk_size=my_chunk_size).execute_query()
```

The exception incl. the traceback:

```
ClientRequestException: ('-1, Microsoft.SharePoint.Client.InvalidClientQueryException', 'The HTTP POST method cannot be used for media resource. The media resource could only be accessed by HTTP GET or updated by HTTP PUT.', "400 Client Error: Bad Request for url: https://mytenant.sharepoint.com/sites/mysite/_api/Web/getFileByServerRelativePath(DecodedUrl='%2Fsites%2Fmysite%2Fmydoclib%2Fmyfile.csv')/$value")
Traceback (most recent call last):
  File "/mypath/office365/runtime/client_request.py", line 58, in execute_query
    response.raise_for_status()
  File "/mypath/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://mytenant.sharepoint.com/sites/mysite/_api/Web/getFileByServerRelativePath(DecodedUrl='%2Fsites%2Fmysite%2Fmydoclib%2Fmyfile.csv')/$value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mypath/mycode.py", line 76, in download
    source_file.download_session(local_file_handle,
  File "/mypath/office365/runtime/client_object.py", line 47, in execute_query
    self.context.execute_query()
  File "/mypath/office365/runtime/client_runtime_context.py", line 187, in execute_query
    self.pending_request().execute_query(qry)
  File "/mypath/office365/runtime/client_request.py", line 62, in execute_query
    raise ClientRequestException(*e.args, response=e.response)
office365.runtime.client_request_exception.ClientRequestException: ('-1, Microsoft.SharePoint.Client.InvalidClientQueryException', 'The HTTP POST method cannot be used for media resource. The media resource could only be accessed by HTTP GET or updated by HTTP PUT.', "400 Client Error: Bad Request for url: https://mytenant.sharepoint.com/sites/mysite/_api/Web/getFileByServerRelativePath(DecodedUrl='%2Fsites%2Fmysite%2Fmydoclib%2Fmyfile.csv')/$value")
```

Thanks for looking into this.

**Comment by niltecedu** [comment]
Experiencing the same!

**Comment by vgrem** [comment]
Greetings,

thank you for reporting it, it indeed became broken in `2.4.4` version due to an introduced bug.

It has been addresed in [`2.5.0` version](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.5.0).
