### ISSUE TITLE
SyntaxError with Python 3.6 using SharePoint

### ISSUE THREAD

**Issue by gendergap** [vgrem/Office365-REST-Python-Client#829]
I am trying to use this module inside an Ansible inventory script to retrieve hosts from a SharePoint list. This works well in a recent (3.11) Python version, but unfortunately I need to rely on Python 3.6 in another environment. There the script fails right away in line 1:

```python
from office365.sharepoint.client_context import ClientContext

# [...] Authentication code like in this example: https://github.com/vgrem/Office365-REST-Python-Client/blob/master/examples/sharepoint/connect_with_client_certificate.py
```

The SyntaxError thrown is this:

```
Traceback (most recent call last):
  File "inventory-from-spo.py", line 1, in <module>
    from office365.sharepoint.client_context import ClientContext
  File "/home/me/.local/lib/python3.6/site-packages/office365/sharepoint/client_context.py", line 16, in <module>
    from office365.runtime.odata.request import ODataRequest
  File "/home/me/.local/lib/python3.6/site-packages/office365/runtime/odata/request.py", line 6, in <module>
    from office365.runtime.client_object import ClientObject
  File "/home/me/.local/lib/python3.6/site-packages/office365/runtime/client_object.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

Is there some kind of compatibility layer one needs to activate?

**Comment by vgrem** [comment]
Closing - Python 3.6 is not supported. `from __future__ import annotations` (PEP 563) requires Python 3.7+, and the library has used it since well before this issue was filed. Python 3.6 reached end-of-life in December 2021.

[v3.0.0](https://github.com/vgrem/office365-rest-python-client/releases/tag/v3.0.0) formalises the minimum supported version as **Python 3.8**.

The fix is to upgrade Python - not the library. For Ansible specifically, Python 3.8+ is available on virtually all modern distros:

```bash
# Ubuntu/Debian
sudo apt install python3.11

# RHEL/CentOS
sudo dnf install python3.11

# or use pyenv for version management
pyenv install 3.11
pyenv local 3.11
```

If upgrading Python on the Ansible controller is not an option, pin to an older version of this library that predates the `from __future__ import annotations` usage - but note that version will also be missing all modern auth flows, security fixes, and has no support.
