### ISSUE TITLE
Using Office-365-REST with ADFS?

### ISSUE THREAD

**Issue by nonprofittechy** [vgrem/Office365-REST-Python-Client#85]
We are using Office365 with ADFS on premises. Does this combination work right now? I'm trying to determine if using this will be a straightforward project or a deep rabbit hole.

I tried running the read_folder_and_files example with a url like this:
https://TENANT.sharepoint.com
and username like this: USERNAME@organization.org

```
No handlers could be found for logger "office365.runtime.auth.saml_token_provider.SamlTokenProvider.process_service_token_response"
Traceback (most recent call last):
  File "test.py", line 37, in <module>
    read_folder_and_files()
  File "test.py", line 15, in read_folder_and_files
    ctx.execute_query()
  File "C:\Python27\lib\site-packages\office365\runtime\client_runtime_context.py", line 33, in execute_query
    self.pending_request.execute_query()
  File "C:\Python27\lib\site-packages\office365\runtime\client_request.py", line 22, in execute_query
    payload = self.execute_query_direct(request)
  File "C:\Python27\lib\site-packages\office365\runtime\client_request.py", line 77, in execute_query_direct
    self.context.authenticate_request(request_options)
  File "C:\Python27\lib\site-packages\office365\runtime\client_runtime_context.py", line 16, in authenticate_request
    self.__auth_context.authenticate_request(request)
  File "C:\Python27\lib\site-packages\office365\runtime\auth\authentication_context.py", line 20, in authenticate_request
    request_options.set_header('Cookie', self.provider.get_authentication_cookie())
  File "C:\Python27\lib\site-packages\office365\runtime\auth\saml_token_provider.py", line 65, in get_authentication_cookie
    return 'FedAuth=' + self.FedAuth + '; rtFa=' + self.rtFa
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**Comment by Cesaaar** [comment]
I solved in this way: https://github.com/vgrem/Office365-REST-Python-Client/issues/76

**Comment by vgrem** [comment]
Greetings,

both **work or school accounts (cloud cloud identity)**  and  **federated account (federated identity)** user accounts are supported nowadays. 


Example:

```
username = "jdoe@contoso.org"
ctx = ClientContext.with_credentials(UserCredential(username, password))

web = ctx.web
ctx.load(web)
ctx.execute_query()
print(web.properties["Url"])

```
