### ISSUE TITLE
ValueError: Unable to load PEM file. 

### ISSUE THREAD

**Issue by XariZaru** [vgrem/Office365-REST-Python-Client#857]
I received the following issue: ```python
Some algorithms requires "pip install cryptography". See https://pyjwt.readthedocs.io/en/latest/installation.html#cryptographic-dependencies-optional
Traceback (most recent call last):
  File "C:\Users\jnguyen-a\AppData\Local\Programs\Python\Python311\Lib\site-packages\jwt\algorithms.py", line 350, in prepare_key
    RSAPrivateKey, load_pem_private_key(key_bytes, password=None)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jnguyen-a\AppData\Local\Programs\Python\Python311\Lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 494, in _handle_key_loading_error
    raise ValueError(
ValueError: ('Could not deserialize key data. The data may be in an incorrect format, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).', [<OpenSSLError(code=503841036, lib=60, reason=524556, reason_text=unsupported)>])

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jnguyen-a\AppData\Local\Programs\Python\Python311\Lib\site-packages\msal\oauth2cli\assertion.py", line 114, in create_normal_assertion
    str_or_bytes = jwt.encode(  # PyJWT 1 returns bytes, PyJWT 2 returns str
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jnguyen-a\AppData\Local\Programs\Python\Python311\Lib\site-packages\jwt\api_jwt.py", line 73, in encode
    return api_jws.encode(
           ^^^^^^^^^^^^^^^
  File "C:\Users\jnguyen-a\AppData\Local\Programs\Python\Python311\Lib\site-packages\jwt\api_jws.py", line 160, in encode
    key = alg_obj.prepare_key(key)
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jnguyen-a\AppData\Local\Programs\Python\Python311\Lib\site-packages\jwt\algorithms.py", line 353, in prepare_key
    return cast(RSAPublicKey, load_pem_public_key(key_bytes))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unable to load PEM file. See https://cryptography.io/en/latest/faq/#why-can-t-i-import-my-pem-file for more details. MalformedFraming```

My .PEM has a format similar to below:
```python
-----BEGIN CERTIFICATE-----
fawefaojsfdojiwefoajsdkljskdfasf=wejfasidofjlksdjfalskdjfkwef
asdkfjeiorjqipofkdkdkdfowifeasdfdkfas
sadfoijweoifjaskldfjlskd
-----END CERTIFICATE-----
```

This is my ClientContext code
```python
cert_credentials = {
    "tenant": TENANT,
    "client_id": CLIENT_ID,
    "thumbprint": THUMBPRINT,
    "private_key": cert_pem_content
}

print(os.getcwd())

ctx = ClientContext("https://COMPANY.sharepoint.com/").with_client_certificate(**cert_credentials)
current_web = ctx.web.get().execute_query()
print("{0}".format(current_web.url))
```

**Comment by dulalbert** [comment]
Hi, 
I had the same problem but it was solved with issue #700.

**Comment by vgrem** [comment]
The PEM file contains only the **public certificate** (`-----BEGIN CERTIFICATE-----`). MSAL needs the **private key** to sign the JWT assertion. The public certificate is what you upload to Azure Portal — not what you pass to `with_client_certificate`.

**Fix - extract the private key from your PFX:**

```bash
# extract private key only
openssl pkcs12 -in certificate.pfx -nocerts -nodes -out private_key.pem

# verify it looks like this:
# -----BEGIN RSA PRIVATE KEY-----  (or -----BEGIN PRIVATE KEY-----)
# ...
# -----END RSA PRIVATE KEY-----
```

**Two valid API signatures:**

```python
# option A — cert_path (file path to PEM with private key)
ctx = ClientContext(site_url).with_client_certificate(
    tenant="company.onmicrosoft.com",
    client_id=CLIENT_ID,
    thumbprint=THUMBPRINT,
    cert_path="./private_key.pem"   # ← path to file
)

# option B — private_key (PEM content as string)
with open("private_key.pem") as f:
    private_key_content = f.read()

ctx = ClientContext(site_url).with_client_certificate(
    tenant="company.onmicrosoft.com",
    client_id=CLIENT_ID,
    thumbprint=THUMBPRINT,
    private_key=private_key_content  # ← string content, not cert_path
)
```

Do not mix `cert_path` and `private_key` - they are mutually exclusive parameters. The `.pem` file must begin with `-----BEGIN RSA PRIVATE KEY-----` or `-----BEGIN PRIVATE KEY-----`, not `-----BEGIN CERTIFICATE-----`.
