### ISSUE TITLE
print "NTLM_NegotiateUnicode set"

### ISSUE THREAD

**Issue by open1312** [vgrem/Office365-REST-Python-Client#96]
While installing Office365-REST_Python-Client its showing one error which says - 

Traceback (most recent call last):
  File "C:\Users\sislam\AppData\Local\Continuum\anaconda3\Scripts\pip-script.py", line 6, in <module>
    from pip import main
  File "C:\Users\sislam\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\__init__.py", line 21, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import DependencyWarning
  File "C:\Users\sislam\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\_vendor\__init__.py", line 86, in <module>
    vendored("requests.packages.urllib3.contrib.ntlmpool")
  File "C:\Users\sislam\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\_vendor\__init__.py", line 33, in vendored
    __import__(vendored_name, globals(), locals(), level=0)
  File "C:\Users\sislam\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\contrib\ntlmpool.py", line 9, in <module>
    from ntlm import ntlm
  File "C:\Users\sislam\AppData\Local\Continuum\anaconda3\lib\site-packages\ntlm\ntlm.py", line 112
    print "NTLM_NegotiateUnicode set"
                                    ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by Bachatero** [comment]
at first glance, you may have s.t. wrong with your anaconda insrallation, consider reinstalling/upgrading ...
